# Generated by Django 5.2.6 on 2026-09-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('part_number', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='components.category')),
            ],
            options={
                'ordering': ['name', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='components.component')),
            ],
            options={
                'ordering': ['attribute'],
            },
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('category', 'reference'), name='unique_component_reference_per_category'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.UniqueConstraint(fields=('component', 'attribute'), name='unique_component_attribute'),
        ),
    ]
