# Generated by Django 5.2.6 on 2026-09-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('url', models.URLField(blank=True)),
                ('date_consulted', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='components.component')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__name', '-date_consulted'],
                'constraints': [models.UniqueConstraint(fields=('component', 'supplier', 'part_number'), name='unique_supplier_offer')],
            },
        ),
    ]
